# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: 'Compilacion'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Laboratorio 02'
- task: DotNetCoreCLI@2
  displayName: 'Publicacion'
  inputs:
    command: 'build'
    publishWebProjects: true
    workingDirectory: '$(System.DefaultWorkingDirectory)/Laboratorio 02'
- task: AzureRmWebAppDeployment@4
  displayName: 'Publicacion'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(2)(a8b530e8-0cae-4192-a61e-129cfff10c11)'
    appType: 'webApp'
    WebAppName: 'ullanos-devops-2024'
    packageForLinux: '$(System.DefaultWorkingDirectory)/Laboratorio 02/**/*.zip'